/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as LinkRouteImport } from './routes/link'
import { Route as GameRouteImport } from './routes/game'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyUserIdRouteImport } from './routes/family.$userId'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyUserIdRoute = FamilyUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => FamilyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/family': typeof FamilyRouteWithChildren
  '/game': typeof GameRoute
  '/link': typeof LinkRoute
  '/nearby': typeof NearbyRoute
  '/rewards': typeof RewardsRoute
  '/family/$userId': typeof FamilyUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/family': typeof FamilyRouteWithChildren
  '/game': typeof GameRoute
  '/link': typeof LinkRoute
  '/nearby': typeof NearbyRoute
  '/rewards': typeof RewardsRoute
  '/family/$userId': typeof FamilyUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/family': typeof FamilyRouteWithChildren
  '/game': typeof GameRoute
  '/link': typeof LinkRoute
  '/nearby': typeof NearbyRoute
  '/rewards': typeof RewardsRoute
  '/family/$userId': typeof FamilyUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/family'
    | '/game'
    | '/link'
    | '/nearby'
    | '/rewards'
    | '/family/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/family'
    | '/game'
    | '/link'
    | '/nearby'
    | '/rewards'
    | '/family/$userId'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/family'
    | '/game'
    | '/link'
    | '/nearby'
    | '/rewards'
    | '/family/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CheckinRoute: typeof CheckinRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  GameRoute: typeof GameRoute
  LinkRoute: typeof LinkRoute
  NearbyRoute: typeof NearbyRoute
  RewardsRoute: typeof RewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/$userId': {
      id: '/family/$userId'
      path: '/$userId'
      fullPath: '/family/$userId'
      preLoaderRoute: typeof FamilyUserIdRouteImport
      parentRoute: typeof FamilyRoute
    }
  }
}

interface FamilyRouteChildren {
  FamilyUserIdRoute: typeof FamilyUserIdRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyUserIdRoute: FamilyUserIdRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CheckinRoute: CheckinRoute,
  FamilyRoute: FamilyRouteWithChildren,
  GameRoute: GameRoute,
  LinkRoute: LinkRoute,
  NearbyRoute: NearbyRoute,
  RewardsRoute: RewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
